### ISSUE TITLE
DEFAULT support

### ISSUE THREAD

**Issue by ghost** [FlipperPA/django-mssql-backend#12]
Please check https://github.com/3YOURMIND/django-pyodbc-azure/commit/5f705ff6395f9ed1d8b82ccf16cc90292a19c024

And now I realize that we also need to override the reverse.

**Comment by ghost** [comment]
And please check this blogpost for why it would be needed: https://medium.com/3yourmind/keeping-django-database-migrations-backward-compatible-727820260dbb

(it's a little more complex now that I look into it deeper again).
So the azure driver actually adds default constraints on the database level, where all other backends don't. This may be something we want to align when contributing to django core.
But until we do, we must actually support proper handling of default values, which we don't without my patch.
Our add default value package already provides a backwards migration for mssql, that no longer works, so I don't think there's anything to fix in the driver.

**Comment by FlipperPA** [comment]
@mes3yd If this ends up being brought into Django core, this will likely be considered. Thank you!
