### ISSUE TITLE
Rational for Integration of a SQL Server backend in Django

### ISSUE THREAD

**Issue by FlipperPA** [FlipperPA/django-mssql-backend#2]
Microsoft SQL Server is the only database of the "big four" which is currently not supported natively by a Django backend engine:

https://db-engines.com/en/ranking

When I first started using Django a few years ago, it was a major point of confusion on which third-party package to use for SQL Server. After trying several engines, we settled on `django-pyodbc-azure`, which has treated us well over the years. @michiya's efforts in maintaining the package are greatly appreciated, however, there is a concern about the lack of communication as to ongoing maintainence of the package.

After many months, it appears it is no longer maintained:
https://github.com/michiya/django-pyodbc-azure/issues/192

I'm currently running in production (as are many others) of a commit on a branch, which was never merged or published to PyPI:
https://github.com/michiya/django-pyodbc-azure/pull/204

More forks and versions are starting to appear:
https://github.com/JordanReiter/django-pyodbc-azure/
https://pypi.org/project/django-mssql-backend/

This duplication of effort and fracturing of the SQL Server on Django community may best be solved by bringing the SQL Server backend into Django.

**Comment by FlipperPA** [comment]
A quote from @Michaya, the maintainer of `django-pyodbc-azure` in 2015:

> I'm very happy to hear that Django is going to receive support from Microsoft to provide first class support for SQL Server and Azure SQL Database! I hope Django will have its official backend implementation for SQL Server and Azure SQL Database, so you can use django-pyodbc-azure as you like to make an official one. And of course I'm willing to help you if there's anything I can.

**Comment by sparrowt** [comment]
See microsoft fork at https://github.com/microsoft/mssql-django/

**Comment by FlipperPA** [comment]
@sparrowt Ha, thanks for the link - that was the issue that spawned that entire project. :)

**Comment by sparrowt** [comment]
Indeed! Just providing a direct link for anyone else who ends up here :)
