### ISSUE TITLE
Support from Microsoft

### ISSUE THREAD

**Issue by FlipperPA** [FlipperPA/django-mssql-backend#8]
Several Microsoft employees have expressed interest in this effort over the years.

Reach out to Microsoft:

* Would they be interested in supporting the Django Software Foundation financially with a yearly donation to support ongoing development work to keep the backend up to date?
* Would they be willing to pledge developers to the effort?

See: https://github.com/michiya/django-pyodbc-azure/issues/190

**Comment by FlipperPA** [comment]
@David-Engel Hoping you can chime in!

**Comment by David-Engel** [comment]
> * Would they be interested in supporting the Django Software Foundation financially with a yearly donation to support ongoing development work to keep the backend up to date?
> * Would they be willing to pledge developers to the effort?

@FlipperPA I know there is interest. It's just been hard to get a commitment without specifics. So that I know what to ask for from the business owners at MS, what amount of yearly financial support would be required/desired? Same question for developer support. What would the size of the commitment look like? Roughly... one person per year? A quarter person? Half a person? It doesn't seem like it would be a full time task to me, but I don't know all the internals. Thanks!

**Comment by FlipperPA** [comment]
@David-Engel I'll reply by email to rope in some folks. Thank you!

**Comment by David-Engel** [comment]
@FlipperPA 

![image](https://user-images.githubusercontent.com/26262303/62903015-37867680-bd16-11e9-8daf-99f8283c6340.png)

**Comment by kevin-olbrich** [comment]
I don't see a reason why FreeTDS needs to be supported (at least if work is needed). Everyone who uses a proprietary database like MSSQL should also be able to also use the original ODBC driver.
The original drivers works flawless while FreeTDS is a reverse-engineering approach.

**Comment by dwasyl** [comment]
+1 to the importance of this. While some use of MSSQL is supported currently, the lack of a properly supported backend definitely discourages hosting on MSSQL platforms. A supported backend would go a long way to resolving this and making MSSQL a more viable option with Django. Simply ensuring feature parity with MySQL or PostgreSQL would be huge. Right now clients running MSSQL have their fingers crossed or get ported to another platform.

**Comment by hannylicious** [comment]
+1 ; we are stuck on 2.1 for the current time being although it's essentially forcing our hand to consider other less supported options because there isn't anything out there really for support of MSSQL (but we're an MS shop, so it is tricky for us).

Would love to see this get integrated into core django!

**Comment by MarcSkovMadsen** [comment]
I'm also stuck on Django 2.1 for now. I'm considering moving to postgres because of this.

**Comment by FlipperPA** [comment]
@dwasyl @hannylicious @MarcSkovMadsen We are still waiting for a reply from Microsoft. They're a large company, so understandably, it takes a little while.

For now, if people need to get onto Django 2.2 for long term support (which will last until April, 2022), you can use this package:

https://github.com/ESSolutions/django-mssql-backend

If Microsoft and/or the Django Software Foundation end up wanting to bring support for SQL Server into core, the `django-mssql-backend` repository is a possible starting point, IMHO.

**Comment by David-Engel** [comment]
@FlipperPA I just wanted to comment here that Microsoft has now funded contributing to this effort. We are in the process of ramping up and collecting information for moving forward.

@warrenchu will be managing and helping to coordinate efforts on our side.

Regards,
David

**Comment by dwasyl** [comment]
@David-Engel that's really great to hear. Look forward to hearing some updates on this as the planning goes forward.

**Comment by sparrowt** [comment]
For future travellers, the microsoft fork is now alive and kicking at https://github.com/microsoft/mssql-django/

**Comment by FlipperPA** [comment]
Since Microsoft has released their backend (HOORAY!), I'm going to close this issue. Thanks to everyone who worked to make this happen! 💯
