### ISSUE TITLE
Introductions: Willing to Help With This Project?

### ISSUE THREAD

**Issue by FlipperPA** [FlipperPA/django-mssql-backend#9]
This thread is to "raise your hand" and introduce yourself as someone who is willing to help out with the effort to get SQL Server support into Django itself, rather than the many forks and packages on PyPI currently available. This causes a lot of confusion for newcomers to Django... hopefully we can solve it!

I'm Tim, an IT Director at The Wharton School. We have quite a few projects which run Django against SQL Server, and have been hindered from upgrading to version 2.2. I'm a member of the Django Software Foundation and have helped organize DjangoCon US for the past few years, including hosting it in Philadelphia at Wharton in 2016.

**Comment by liquidsunshine** [comment]
Hi Tim!  I'm Donny -- I have a few projects at work that use Django on SQL Server, and I've been using the django-pyodbc-azure.  I've been watching the conversations about maintainability and core support with interest.

I'm definitely interested in helping, but I feel a little out of my depth.  I've used Django for a few years and I have some experience with SQL Server, but I haven't looked too closely at the guts of the database code.

Any suggestions for where I can get my feet wet?

**Comment by seancallaway** [comment]
I'm Sean, a Systems Engineer at an outdoor retailer, and am in a similar boat to @liquidsunshine: a user of django-pyodbc-azure in projects at work. I don't know where to start re: hacking at Django. I do have time to offer in my off time and could _probably_ sell getting time to work on this at work to management.

**Comment by Virtual1** [comment]
Hi there, I'm Jessica, learning to code. I'm a  freelancer, supporting accounting software with a SQL Server backend and I'm tinkering around to see if I can add features with my own little add-ons. Willing to help out where I can.

**Comment by FlipperPA** [comment]
It's great to meet you all! I'm hoping to have some news to share within a few weeks, probably after DjangoCon US (September 22nd - 27th). Looking forward to collaborating with all of you!

**Comment by knguyen1794** [comment]
hi Tim and everyone, this is Kelvin. I have been using Django with SQL Server for a couple of years now. I'm more than willing to help with this project wherever I can.

**Comment by FlipperPA** [comment]
Welcome, @knguyen1794! We're still waiting on several involved parties to figure some things out. Once I have more to share, I'll do so here. Thanks for dropping in!

**Comment by briandkim93** [comment]
Hi Tim. Brian here. I've only been using Django + MSSQL for a couple of years now but it's been fairly immersive. I'd love to contribute if you're still looking for volunteers.

Also, thanks for your participation in DjangoCon 2019! It was my first time there and a great experience. Unfortunately couldn't make it to your talk, but I'm looking forward to checking it out once it's been uploaded.

**Comment by joaofrancese** [comment]
Hi everyone, João Pedro here. In the past six years I've been leading a team using Django + SQL Server  to power our proprietary financial-services software. I currently maintain my fork of django-mssql (haven't migrated to django-pyodbc) and I'd love to see first class support for SQL Server in Django. I could offer some time from me and my team for development & testing in this project.

**Comment by hannylicious** [comment]
Hello everyone, Hanny (Chris) here. I (like others) use Django with MS SQL and would love to see native support for it in Django! I am primarily a Django dev, but I am willing to help how I can, although my knowledge on this side of things may not be as deep as others who have developed libraries in use by various communities. Willing to learn, happy to help how I can.

**Comment by SeanMartz** [comment]
Hello, Sean here. I'm primarily a dotnet developer - but I've fallen in love with Django and the Django Community. I think First Class support of SQL Server would be great to be able to sell Django as an option to DotNet Shops. I'm very happy to learn and assist in any way possible.

I think we might want to consider creating a Django Enhancement Proposal for this. Does anyone have any experience with DEPS?

ref: https://github.com/django/deps

**Comment by Finndersen** [comment]
Hi all, I'm a software engineer using Django and MSSQL, would love to see some better support and integration going forwards, willing to help out where I can..
Tim what's the status at the moment?

**Comment by FlipperPA** [comment]
Just an update: we are still waiting for a reply from Microsoft. They're a large company, so understandably, it takes a little while.

For now, if people need to get onto Django 2.2 for long term support (which will last until April, 2022), you can use this package:

https://github.com/ESSolutions/django-mssql-backend

If Microsoft and/or the Django Software Foundation end up wanting to bring support for SQL Server into core, the `django-mssql-backend` repository is a possible starting point, IMHO.

The `django-mssql-backend` is currently being developed and support for Django 3.0 is being worked on: https://github.com/ESSolutions/django-mssql-backend/issues/18

**Comment by kummerer94** [comment]
@FlipperPA: Thank you for all the work. Really appreciate the information and the link to the working backend for Django 2.2. That helps a lot.

**Comment by gonthe** [comment]
Hi @FlipperPA, I work for Microsoft. Is there any place I can help raise voice for this. We have been stuck on Django 2.1 in our project and are not sure how stable ESSolutions/django-mssql-backend is to use

**Comment by gonthe** [comment]
I also heard django-pyodbc-azure author joined Django to provide direct support to SQL server, any truth to it?

**Comment by kummerer94** [comment]
@gonthe Been using ESSolutions/django-mssql-backend for a while now and they even added Django 3.0 support now. No problems on my end so far.

**Comment by FlipperPA** [comment]
Howdy @gonthe! I've also been using the backend @kummerer94 is using, and haven't had any problems, but I only use SQL Server as a secondary database.

AFAIK, there isn't any truth that the author of `django-pyodbc-azure` has contributed directly to Django. Michiya, the author, has been radio silent for quite a while now and no one has been able to get in touch with him. You may have been hearing about me - I was a contributor to `django-pyodbc-azure` and am very involved with the Django community. :)

@gonthe, could you shoot me an email when you get a chance so we can discuss this offline? tim+github@pyphilly.org :)

**Comment by hannylicious** [comment]
@gonthe I also have been using ESSolutions/django-mssql-backend for a while with Django 3.x and have ran into no issues as of yet. I'm using it in a place that is a MS shop - so SQL Server is all they use (primary db). Seems good to me! 👍
